var availability=availability||{};availability.AvailabilityIterator=availability.AvailabilityIterator||function(g){return function(a){var a=a||{},e={},c=new availability.MergingStatusIterator({it:new availability.TimeWindowsIterator({availability:a.availability||null,cal:a.cal||null})});e.hasNext=function(){return c.hasNext()};e.next=function(){return c.next()};return e}(g)};availability=availability||{};
availability.DateTimeWindowsIterator=availability.DateTimeWindowsIterator||function(g){return function(a){function e(a,d){this.index=a;this.isDummyBefore=d}function c(a){return(new timezoneJS.Date(a.year,a.month-1,a.day,a.hour,a.minute,i)).getTime()}var a=a||{},f=a.timeWindows||[],d=a.cal||null,a={};e.prototype.advance=function(){this.isDummyBefore?this.isDummyBefore=!1:(this.isDummyBefore=!0,++this.index)};var i=d.getTimezone(),b=null;if(0<f.length){for(var d=d.getTime(),h=0,j=f.length;h<j;++h){var g=
f[h];if(d<c(g.start)){b=new e(h,!0);break}else if(d<c(g.end)){b=new e(h,!1);break}}null===b&&(b=new e(f.length,!0))}else b=new e(0,!0);a.hasNext=function(){return b.isDummyBefore||b.index<f.length};a.next=function(){if(b.index===f.length)result={status:availability.STATUS_UNKNOWN,until:null};else{var a=f[b.index];result=b.isDummyBefore?{status:availability.STATUS_UNKNOWN,until:c(a.start)}:{status:a.available?availability.STATUS_AVAILABLE:availability.STATUS_UNAVAILABLE,until:c(a.end),reason:a.reason,
comment:a.comment}}b.advance();return result};return a}(g)};availability=availability||{};
availability.MergingStatusIterator=availability.MergingStatusIterator||function(g){return function(a){function e(a,c){if(a){if(!c)return!1}else return c?!1:!0;for(var b in a)if(a[b]!==c[b])return!1;for(b in c)if(c[b]!==a[b])return!1;return!0}var a=a||{},c=a.it||null,a={},f=null!==c&&c.hasNext()?c.next():null;a.hasNext=function(){return null!=f};a.next=function(){for(var a=f;;){if(!c.hasNext()){f=null;break}f=c.next();if(!(f.status===a.status&&f.reason===a.reason&&e(f.comment,a.comment)))break;a.until=
f.until}return a};return a}(g)};availability=availability||{};
availability.Period=availability.Period||function(g){return function(a){var a=a||{},e=a.days||0,c=a.hours||0,f=a.minutes||0,d={getDays:function(){return e},getHours:function(){return c},getMinutes:function(){return f},toStandardMinutes:function(){return 60*(24*e+c)+f},plus:function(a){return new availability.Period({days:e+(a.days||0),hours:c+(a.hours||0),minutes:f+(a.minutes||0)})},plusMinutes:function(a){return d.plus({minutes:a})},normalizedStandard:function(){var a=e,b=c,d=f;extraHours=Math.floor(d/
60);var d=d-60*extraHours,b=b+extraHours,j=Math.floor(b/24);return new availability.Period({days:a+j,hours:b-24*j,minutes:d})}};return d}(g)};availability=availability||{};availability.STATUS_UNAVAILABLE="unavailable";availability.STATUS_AVAILABLE="available";availability.STATUS_UNKNOWN="unknown";availability=availability||{};
availability.TimeWindowsIterator=availability.TimeWindowsIterator||function(g){return function(a){var a=a||{},e=a.availability||null,a=a.cal||null,c={},f=new availability.WeeklyTimeWindowsIterator({cal:a,weekly:e.weekly}),d=new availability.DateTimeWindowsIterator({cal:a,timeWindows:e.exceptions}),i=f.next(),b=d.next(),g=!0;c.hasNext=function(){return g};c.next=function(){if(!b.until){var a=i;f.hasNext()?i=f.next():g=!1;return a}if(availability.STATUS_UNKNOWN!==b.status){a=b;for(b=d.next();i.until&&
i.until<=a.until;)i=f.next();return a}if(!i.until||i.until>b.until)return a=b,b=d.next(),{status:i.status,until:a.until};i.until<b.until||(b=d.next());a=i;i=f.next();return a};return c}(g)};availability=availability||{};availability.HOUR=60;availability.DAY=24*availability.HOUR;availability.WEEK=7*availability.DAY;availability.SUNDAY=0*availability.DAY;availability.MONDAY=1*availability.DAY;availability.TUESDAY=2*availability.DAY;availability.WEDNESDAY=3*availability.DAY;availability.THURSDAY=4*availability.DAY;availability.FRIDAY=5*availability.DAY;availability.SATURDAY=6*availability.DAY;
availability.WeeklyTimeWindowsIterator=availability.WeeklyTimeWindowsIterator||function(g){return function(a){var a=a||{},e=a.weekly||[],c=a.cal||null,a={},c=c.clone(),f=!0,d=[],g=null;if(0===e.length)d.push({minuteOfWeek:0,durationMins:availability.WEEK,status:availability.STATUS_AVAILABLE}),g=!0;else{for(var b=0,h=0,j=e.length;h<j;++h){var k=e[h];k.minuteOfWeek>b&&d.push({minuteOfWeek:b,durationMins:k.minuteOfWeek-b,status:availability.STATUS_UNAVAILABLE});d.push({minuteOfWeek:k.minuteOfWeek,durationMins:k.durationMins,
status:availability.STATUS_AVAILABLE});b=k.minuteOfWeek+k.durationMins}b<availability.WEEK&&d.push({minuteOfWeek:b,durationMins:availability.WEEK-b,status:availability.STATUS_UNAVAILABLE});g=d[0].status===d[d.length-1].status}var l=1===d.length;a.hasNext=function(){return f};a.next=function(){if(l)return f=!1,{status:d[0].status,until:null};for(var a=(c.getDay()-availability.SUNDAY)*availability.DAY+c.getHours()*availability.HOUR+c.getMinutes(),b=0,e=d.length;b<e;){var h=b+e>>>1;d[h].minuteOfWeek+
d[h].durationMins<=a?b=h+1:e=h}b=d[b];e=b.minuteOfWeek+b.durationMins;e===availability.WEEK&&(e=g?d[0].minuteOfWeek+d[0].durationMins:0);a=e-a;0>a&&(a+=availability.WEEK);for(a=(new availability.Period({days:c.getDate(),hours:c.getHours(),minutes:c.getMinutes()})).plusMinutes(a).normalizedStandard();;){c.setDate(a.getDays());c.setHours(a.getHours());c.setMinutes(a.getMinutes());c.setSeconds(0);c.setMilliseconds(0);if(c.getHours()===a.getHours()&&c.getMinutes()===a.getMinutes())break;a=a.plusMinutes(1).normalizedStandard();
++e}return{status:b.status,until:c.getTime()}};return a}(g)};
