var Base64=function(){return{encode:function(a){var b="",c,d,e,h,g,m,n=0;do c=a.charCodeAt(n++),d=a.charCodeAt(n++),e=a.charCodeAt(n++),h=c>>2,c=(c&3)<<4|d>>4,g=(d&15)<<2|e>>6,m=e&63,isNaN(d)?g=m=64:isNaN(e)&&(m=64),b=b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(g)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(m);
while(n<a.length);return b},decode:function(a){var b="",c,d,e,h,g,m=0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");do c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),h="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(m++)),c=c<<2|d>>4,d=(d&15)<<
4|h>>2,e=(h&3)<<6|g,b+=String.fromCharCode(c),64!=h&&(b+=String.fromCharCode(d)),64!=g&&(b+=String.fromCharCode(e));while(m<a.length);return b}}}();var hexcase=0,b64pad="=",chrsz=8;function hex_sha1(a){return binb2hex(core_sha1(str2binb(a),a.length*chrsz))}function b64_sha1(a){return binb2b64(core_sha1(str2binb(a),a.length*chrsz))}function str_sha1(a){return binb2str(core_sha1(str2binb(a),a.length*chrsz))}function hex_hmac_sha1(a,b){return binb2hex(core_hmac_sha1(a,b))}function b64_hmac_sha1(a,b){return binb2b64(core_hmac_sha1(a,b))}function str_hmac_sha1(a,b){return binb2str(core_hmac_sha1(a,b))}
function sha1_vm_test(){return"a9993e364706816aba3e25717850c26c9cd0d89d"==hex_sha1("abc")}
function core_sha1(a,b){a[b>>5]|=128<<24-b%32;a[(b+64>>9<<4)+15]=b;var c=Array(80),d=1732584193,e=-271733879,h=-1732584194,g=271733878,m=-1009589776,n,o,p,q,r,s,t,f;for(n=0;n<a.length;n+=16){q=d;r=e;s=h;t=g;f=m;for(o=0;80>o;o++)c[o]=16>o?a[n+o]:rol(c[o-3]^c[o-8]^c[o-14]^c[o-16],1),p=safe_add(safe_add(rol(d,5),sha1_ft(o,e,h,g)),safe_add(safe_add(m,c[o]),sha1_kt(o))),m=g,g=h,h=rol(e,30),e=d,d=p;d=safe_add(d,q);e=safe_add(e,r);h=safe_add(h,s);g=safe_add(g,t);m=safe_add(m,f)}return[d,e,h,g,m]}
function sha1_ft(a,b,c,d){return 20>a?b&c|~b&d:40>a?b^c^d:60>a?b&c|b&d|c&d:b^c^d}function sha1_kt(a){return 20>a?1518500249:40>a?1859775393:60>a?-1894007588:-899497514}function core_hmac_sha1(a,b){var c=str2binb(a);16<c.length&&(c=core_sha1(c,a.length*chrsz));for(var d=Array(16),e=Array(16),h=0;16>h;h++)d[h]=c[h]^909522486,e[h]=c[h]^1549556828;c=core_sha1(d.concat(str2binb(b)),512+b.length*chrsz);return core_sha1(e.concat(c),672)}
function safe_add(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535}function rol(a,b){return a<<b|a>>>32-b}function str2binb(a){for(var b=[],c=(1<<chrsz)-1,d=0;d<a.length*chrsz;d+=chrsz)b[d>>5]|=(a.charCodeAt(d/chrsz)&c)<<32-chrsz-d%32;return b}function binb2str(a){for(var b="",c=(1<<chrsz)-1,d=0;d<32*a.length;d+=chrsz)b+=String.fromCharCode(a[d>>5]>>>32-chrsz-d%32&c);return b}
function binb2hex(a){for(var b=hexcase?"0123456789ABCDEF":"0123456789abcdef",c="",d=0;d<4*a.length;d++)c+=b.charAt(a[d>>2]>>8*(3-d%4)+4&15)+b.charAt(a[d>>2]>>8*(3-d%4)&15);return c}function binb2b64(a){for(var b="",c,d,e=0;e<4*a.length;e+=3){c=(a[e>>2]>>8*(3-e%4)&255)<<16|(a[e+1>>2]>>8*(3-(e+1)%4)&255)<<8|a[e+2>>2]>>8*(3-(e+2)%4)&255;for(d=0;4>d;d++)b=8*e+6*d>32*a.length?b+b64pad:b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>6*(3-d)&63)}return b};var MD5=function(){var a=function(a,b){var c=(a&65535)+(b&65535);return(a>>16)+(b>>16)+(c>>16)<<16|c&65535},b=function(a){for(var b=[],c=0;c<8*a.length;c+=8)b[c>>5]|=(a.charCodeAt(c/8)&255)<<c%32;return b},c=function(a){for(var b="",c=0;c<32*a.length;c+=8)b+=String.fromCharCode(a[c>>5]>>>c%32&255);return b},d=function(a){for(var b="",c=0;c<4*a.length;c++)b+="0123456789abcdef".charAt(a[c>>2]>>8*(c%4)+4&15)+"0123456789abcdef".charAt(a[c>>2]>>8*(c%4)&15);return b},e=function(a){for(var b="",c,d,f=0;f<
4*a.length;f+=3){c=(a[f>>2]>>8*(f%4)&255)<<16|(a[f+1>>2]>>8*((f+1)%4)&255)<<8|a[f+2>>2]>>8*((f+2)%4)&255;for(d=0;4>d;d++)b=8*f+6*d>32*a.length?b+"":b+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(c>>6*(3-d)&63)}return b},h=function(b,c,d,e,f,j){b=a(a(c,b),a(e,j));return a(b<<f|b>>>32-f,d)},g=function(a,b,c,d,f,e,g){return h(b&c|~b&d,a,b,f,e,g)},m=function(a,b,c,d,f,e,g){return h(b&d|c&~d,a,b,f,e,g)},n=function(a,b,c,d,f,e,g){return h(c^(b|~d),a,b,f,e,g)},o=function(b,c){b[c>>
5]|=128<<c%32;b[(c+64>>>9<<4)+14]=c;for(var d=1732584193,e=-271733879,f=-1732584194,j=271733878,o,p,u,v,l=0;l<b.length;l+=16)o=d,p=e,u=f,v=j,d=g(d,e,f,j,b[l+0],7,-680876936),j=g(j,d,e,f,b[l+1],12,-389564586),f=g(f,j,d,e,b[l+2],17,606105819),e=g(e,f,j,d,b[l+3],22,-1044525330),d=g(d,e,f,j,b[l+4],7,-176418897),j=g(j,d,e,f,b[l+5],12,1200080426),f=g(f,j,d,e,b[l+6],17,-1473231341),e=g(e,f,j,d,b[l+7],22,-45705983),d=g(d,e,f,j,b[l+8],7,1770035416),j=g(j,d,e,f,b[l+9],12,-1958414417),f=g(f,j,d,e,b[l+10],17,
-42063),e=g(e,f,j,d,b[l+11],22,-1990404162),d=g(d,e,f,j,b[l+12],7,1804603682),j=g(j,d,e,f,b[l+13],12,-40341101),f=g(f,j,d,e,b[l+14],17,-1502002290),e=g(e,f,j,d,b[l+15],22,1236535329),d=m(d,e,f,j,b[l+1],5,-165796510),j=m(j,d,e,f,b[l+6],9,-1069501632),f=m(f,j,d,e,b[l+11],14,643717713),e=m(e,f,j,d,b[l+0],20,-373897302),d=m(d,e,f,j,b[l+5],5,-701558691),j=m(j,d,e,f,b[l+10],9,38016083),f=m(f,j,d,e,b[l+15],14,-660478335),e=m(e,f,j,d,b[l+4],20,-405537848),d=m(d,e,f,j,b[l+9],5,568446438),j=m(j,d,e,f,b[l+14],
9,-1019803690),f=m(f,j,d,e,b[l+3],14,-187363961),e=m(e,f,j,d,b[l+8],20,1163531501),d=m(d,e,f,j,b[l+13],5,-1444681467),j=m(j,d,e,f,b[l+2],9,-51403784),f=m(f,j,d,e,b[l+7],14,1735328473),e=m(e,f,j,d,b[l+12],20,-1926607734),d=h(e^f^j,d,e,b[l+5],4,-378558),j=h(d^e^f,j,d,b[l+8],11,-2022574463),f=h(j^d^e,f,j,b[l+11],16,1839030562),e=h(f^j^d,e,f,b[l+14],23,-35309556),d=h(e^f^j,d,e,b[l+1],4,-1530992060),j=h(d^e^f,j,d,b[l+4],11,1272893353),f=h(j^d^e,f,j,b[l+7],16,-155497632),e=h(f^j^d,e,f,b[l+10],23,-1094730640),
d=h(e^f^j,d,e,b[l+13],4,681279174),j=h(d^e^f,j,d,b[l+0],11,-358537222),f=h(j^d^e,f,j,b[l+3],16,-722521979),e=h(f^j^d,e,f,b[l+6],23,76029189),d=h(e^f^j,d,e,b[l+9],4,-640364487),j=h(d^e^f,j,d,b[l+12],11,-421815835),f=h(j^d^e,f,j,b[l+15],16,530742520),e=h(f^j^d,e,f,b[l+2],23,-995338651),d=n(d,e,f,j,b[l+0],6,-198630844),j=n(j,d,e,f,b[l+7],10,1126891415),f=n(f,j,d,e,b[l+14],15,-1416354905),e=n(e,f,j,d,b[l+5],21,-57434055),d=n(d,e,f,j,b[l+12],6,1700485571),j=n(j,d,e,f,b[l+3],10,-1894986606),f=n(f,j,d,e,
b[l+10],15,-1051523),e=n(e,f,j,d,b[l+1],21,-2054922799),d=n(d,e,f,j,b[l+8],6,1873313359),j=n(j,d,e,f,b[l+15],10,-30611744),f=n(f,j,d,e,b[l+6],15,-1560198380),e=n(e,f,j,d,b[l+13],21,1309151649),d=n(d,e,f,j,b[l+4],6,-145523070),j=n(j,d,e,f,b[l+11],10,-1120210379),f=n(f,j,d,e,b[l+2],15,718787259),e=n(e,f,j,d,b[l+9],21,-343485551),d=a(d,o),e=a(e,p),f=a(f,u),j=a(j,v);return[d,e,f,j]},p=function(a,c){var d=b(a);16<d.length&&(d=o(d,8*a.length));for(var e=Array(16),f=Array(16),g=0;16>g;g++)e[g]=d[g]^909522486,
f[g]=d[g]^1549556828;d=o(e.concat(b(c)),512+8*c.length);return o(f.concat(d),640)};return{hexdigest:function(a){return d(o(b(a),8*a.length))},b64digest:function(a){return e(o(b(a),8*a.length))},hash:function(a){return c(o(b(a),8*a.length))},hmac_hexdigest:function(a,b){return d(p(a,b))},hmac_b64digest:function(a,b){return e(p(a,b))},hmac_hash:function(a,b){return c(p(a,b))},test:function(){return"900150983cd24fb0d6963f7d28e17f72"===MD5.hexdigest("abc")}}}();Function.prototype.bind||(Function.prototype.bind=function(a){var b=this,c=Array.prototype.slice,d=Array.prototype.concat,e=c.call(arguments,1);return function(){return b.apply(a?a:this,d.call(e,c.call(arguments,0)))}});Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length,d=Number(b)||0,d=d<0?Math.ceil(d):Math.floor(d);for(d<0&&(d=d+c);d<c;d++)if(d in this&&this[d]===a)return d;return-1});var Strophe;function $build(a,b){return new Strophe.Builder(a,b)}
function $msg(a){return new Strophe.Builder("message",a)}function $iq(a){return new Strophe.Builder("iq",a)}function $pres(a){return new Strophe.Builder("presence",a)}
Strophe={VERSION:"1.0.2b",NS:{HTTPBIND:"http://jabber.org/protocol/httpbind",BOSH:"urn:xmpp:xbosh",CLIENT:"jabber:client",AUTH:"jabber:iq:auth",ROSTER:"jabber:iq:roster",PROFILE:"jabber:iq:profile",DISCO_INFO:"http://jabber.org/protocol/disco#info",DISCO_ITEMS:"http://jabber.org/protocol/disco#items",MUC:"http://jabber.org/protocol/muc",SASL:"urn:ietf:params:xml:ns:xmpp-sasl",STREAM:"http://etherx.jabber.org/streams",BIND:"urn:ietf:params:xml:ns:xmpp-bind",SESSION:"urn:ietf:params:xml:ns:xmpp-session",
VERSION:"jabber:iq:version",STANZAS:"urn:ietf:params:xml:ns:xmpp-stanzas",XHTML_IM:"http://jabber.org/protocol/xhtml-im",XHTML:"http://www.w3.org/1999/xhtml"},XHTML:{tags:"a blockquote br cite em img li ol p span strong ul body".split(" "),attributes:{a:["href"],blockquote:["style"],br:[],cite:["style"],em:[],img:["src","alt","style","height","width"],li:["style"],ol:["style"],p:["style"],span:["style"],strong:[],ul:["style"],body:[]},css:"background-color color font-family font-size font-style font-weight margin-left margin-right text-align text-decoration".split(" "),
validTag:function(a){for(var b=0;b<Strophe.XHTML.tags.length;b++)if(a==Strophe.XHTML.tags[b])return true;return false},validAttribute:function(a,b){if(typeof Strophe.XHTML.attributes[a]!=="undefined"&&Strophe.XHTML.attributes[a].length>0)for(var c=0;c<Strophe.XHTML.attributes[a].length;c++)if(b==Strophe.XHTML.attributes[a][c])return true;return false},validCSS:function(a){for(var b=0;b<Strophe.XHTML.css.length;b++)if(a==Strophe.XHTML.css[b])return true;return false}},addNamespace:function(a,b){Strophe.NS[a]=
b},Status:{ERROR:0,CONNECTING:1,CONNFAIL:2,AUTHENTICATING:3,AUTHFAIL:4,CONNECTED:5,DISCONNECTED:6,DISCONNECTING:7,ATTACHED:8},LogLevel:{DEBUG:0,INFO:1,WARN:2,ERROR:3,FATAL:4},ElementType:{NORMAL:1,TEXT:3,CDATA:4,FRAGMENT:11},TIMEOUT:1.1,SECONDARY_TIMEOUT:0.1,forEachChild:function(a,b,c){var d,e;for(d=0;d<a.childNodes.length;d++){e=a.childNodes.item(d);e.nodeType==Strophe.ElementType.NORMAL&&(!b||this.isTagEqual(e,b))&&c(e)}},isTagEqual:function(a,b){return a.tagName.toLowerCase()==b.toLowerCase()},
_xmlGenerator:null,_makeGenerator:function(){return xml.create("jabber:client","strophe",null)},xmlGenerator:function(){if(!Strophe._xmlGenerator)Strophe._xmlGenerator=Strophe._makeGenerator();return Strophe._xmlGenerator},xmlElement:function(a){if(!a)return null;var b=Strophe.xmlGenerator().createElement(a),c,d,e;for(c=1;c<arguments.length;c++)if(arguments[c])if(typeof arguments[c]=="string"||typeof arguments[c]=="number")b.appendChild(Strophe.xmlTextNode(arguments[c]));else if(typeof arguments[c]==
"object"&&typeof arguments[c].sort=="function")for(d=0;d<arguments[c].length;d++)typeof arguments[c][d]=="object"&&typeof arguments[c][d].sort=="function"&&b.setAttribute(arguments[c][d][0],""+arguments[c][d][1]);else if(typeof arguments[c]=="object")for(e in arguments[c])arguments[c].hasOwnProperty(e)&&b.setAttribute(e,""+arguments[c][e]);return b},xmlescape:function(a){a=a.replace(/\&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/'/g,"&apos;");return a=a.replace(/"/g,
"&quot;")},xmlTextNode:function(a){return Strophe.xmlGenerator().createTextNode(a)},xmlHtmlNode:function(a){if(window.DOMParser){parser=new DOMParser;node=parser.parseFromString(a,"text/xml")}else{node=new ActiveXObject("Microsoft.XMLDOM");node.async="false";node.loadXML(a)}return node},getText:function(a){if(!a)return null;var b="";a.childNodes.length===0&&a.nodeType==Strophe.ElementType.TEXT&&(b=b+a.nodeValue);for(var c=0;c<a.childNodes.length;c++)a.childNodes.item(c).nodeType==Strophe.ElementType.TEXT&&
(b=b+a.childNodes.item(c).nodeValue);return Strophe.xmlescape(b)},copyElement:function(a){var b,c;if(a.nodeType==Strophe.ElementType.NORMAL){c=Strophe.xmlElement(a.tagName);for(b=0;b<a.attributes.length;b++)c.setAttribute(a.attributes.item(b).nodeName.toLowerCase(),a.attributes.item(b).value);for(b=0;b<a.childNodes.length;b++)c.appendChild(Strophe.copyElement(a.childNodes.item(b)))}else a.nodeType==Strophe.ElementType.TEXT&&(c=Strophe.xmlGenerator().createTextNode(a.nodeValue));return c},createHtml:function(a){var b,
c,d,e,h,g,m,n,o,p,q;if(a.nodeType==Strophe.ElementType.NORMAL){e=a.nodeName.toLowerCase();if(Strophe.XHTML.validTag(e))try{c=Strophe.xmlElement(e);for(b=0;b<Strophe.XHTML.attributes[e].length;b++){h=Strophe.XHTML.attributes[e][b];g=a.getAttribute(h);if(!(typeof g=="undefined"||g===null||g===""||g===false||g===0)){if(h=="style"&&typeof g=="object"&&typeof g.cssText!="undefined")g=g.cssText;if(h=="style"){m=[];n=g.split(";");for(d=0;d<n.length;d++){o=n[d].split(":");p=o[0].replace(/^\s*/,"").replace(/\s*$/,
"").toLowerCase();if(Strophe.XHTML.validCSS(p)){q=o[1].replace(/^\s*/,"").replace(/\s*$/,"");m.push(p+": "+q)}}if(m.length>0){g=m.join("; ");c.setAttribute(h,g)}}else c.setAttribute(h,g)}}for(b=0;b<a.childNodes.length;b++)c.appendChild(Strophe.createHtml(a.childNodes.item(b)))}catch(r){c=Strophe.xmlTextNode("")}else{c=Strophe.xmlGenerator().createDocumentFragment();for(b=0;b<a.childNodes.length;b++)c.appendChild(Strophe.createHtml(a.childNodes.item(b)))}}else if(a.nodeType==Strophe.ElementType.FRAGMENT){c=
Strophe.xmlGenerator().createDocumentFragment();for(b=0;b<a.childNodes.length;b++)c.appendChild(Strophe.createHtml(a.childNodes.item(b)))}else a.nodeType==Strophe.ElementType.TEXT&&(c=Strophe.xmlTextNode(a.nodeValue));return c},escapeNode:function(a){return a.replace(/^\s+|\s+$/g,"").replace(/\\/g,"\\5c").replace(/ /g,"\\20").replace(/\"/g,"\\22").replace(/\&/g,"\\26").replace(/\'/g,"\\27").replace(/\//g,"\\2f").replace(/:/g,"\\3a").replace(/</g,"\\3c").replace(/>/g,"\\3e").replace(/@/g,"\\40")},
unescapeNode:function(a){return a.replace(/\\20/g," ").replace(/\\22/g,'"').replace(/\\26/g,"&").replace(/\\27/g,"'").replace(/\\2f/g,"/").replace(/\\3a/g,":").replace(/\\3c/g,"<").replace(/\\3e/g,">").replace(/\\40/g,"@").replace(/\\5c/g,"\\")},getNodeFromJid:function(a){return a.indexOf("@")<0?null:a.split("@")[0]},getDomainFromJid:function(a){a=Strophe.getBareJidFromJid(a);if(a.indexOf("@")<0)return a;a=a.split("@");a.splice(0,1);return a.join("@")},getResourceFromJid:function(a){a=a.split("/");
if(a.length<2)return null;a.splice(0,1);return a.join("/")},getBareJidFromJid:function(a){return a?a.split("/")[0]:null},log:function(){},debug:function(a){this.log(this.LogLevel.DEBUG,a)},info:function(a){this.log(this.LogLevel.INFO,a)},warn:function(a){this.log(this.LogLevel.WARN,a)},error:function(a){this.log(this.LogLevel.ERROR,a)},fatal:function(a){this.log(this.LogLevel.FATAL,a)},serialize:function(a){var b;if(!a)return null;typeof a.tree==="function"&&(a=a.tree());var c=a.nodeName,d,e;a.getAttribute("_realname")&&
(c=a.getAttribute("_realname"));b="<"+c;for(d=0;d<a.attributes.length;d++)a.attributes.item(d).nodeName!="_realname"&&(b=b+(" "+a.attributes.item(d).nodeName.toLowerCase()+"='"+a.attributes.item(d).value.replace(/&/g,"&amp;").replace(/\'/g,"&apos;").replace(/>/g,"&gt;").replace(/</g,"&lt;")+"'"));if(a.childNodes.length>0){b=b+">";for(d=0;d<a.childNodes.length;d++){e=a.childNodes.item(d);switch(e.nodeType){case Strophe.ElementType.NORMAL:b=b+Strophe.serialize(e);break;case Strophe.ElementType.TEXT:b=
b+Strophe.xmlescape(e.nodeValue);break;case Strophe.ElementType.CDATA:b=b+("<![CDATA["+e.nodeValue+"]]\>")}}b=b+("</"+c+">")}else b=b+"/>";return b},_requestId:0,_connectionPlugins:{},addConnectionPlugin:function(a,b){Strophe._connectionPlugins[a]=b},Builder:function(a,b){if(a=="presence"||a=="message"||a=="iq")b&&!b.xmlns?b.xmlns=Strophe.NS.CLIENT:b||(b={xmlns:Strophe.NS.CLIENT});this.node=this.nodeTree=Strophe.xmlElement(a,b)}};
Strophe.Builder.prototype={tree:function(){return this.nodeTree},toString:function(){return Strophe.serialize(this.nodeTree)},up:function(){this.node=this.node.parentNode;return this},attrs:function(a){for(var b in a)a.hasOwnProperty(b)&&this.node.setAttribute(b,""+a[b]);return this},c:function(a,b,c){a=Strophe.xmlElement(a,b,c);this.node.appendChild(a);if(!c)this.node=a;return this},cnode:function(a){var b=Strophe.xmlGenerator();try{var c=b.importNode!==void 0}catch(d){c=false}a=c?b.importNode(a,
true):Strophe.copyElement(a);this.node.appendChild(a);this.node=a;return this},t:function(a){this.node.appendChild(Strophe.xmlTextNode(a));return this},h:function(a){var b=document.createElement("body");b.innerHTML=a;for(a=Strophe.createHtml(b);a.childNodes.length>0;)this.node.appendChild(a.childNodes.item(0));return this}};
Strophe.Handler=function(a,b,c,d,e,h,g){this.handler=a;this.ns=b;this.name=c;this.type=d;this.id=e;this.options=g||{matchbare:false};if(!this.options.matchBare)this.options.matchBare=false;this.from=this.options.matchBare?h?Strophe.getBareJidFromJid(h):null:h;this.user=true};
Strophe.Handler.prototype={isMatch:function(a){var b,c=null,c=this.options.matchBare?Strophe.getBareJidFromJid(a.getAttribute("from")):a.getAttribute("from");b=false;if(this.ns){var d=this;Strophe.forEachChild(a,null,function(a){a.getAttribute("xmlns")==d.ns&&(b=true)});b=b||a.getAttribute("xmlns")==this.ns}else b=true;return b&&(!this.name||Strophe.isTagEqual(a,this.name))&&(!this.type||a.getAttribute("type")==this.type)&&(!this.id||a.getAttribute("id")==this.id)&&(!this.from||c==this.from)?true:
false},run:function(a){var b=null;try{b=this.handler(a)}catch(c){if(c.sourceURL)Strophe.fatal("error: "+this.handler+" "+c.sourceURL+":"+c.line+" - "+c.name+": "+c.message);else if(c.fileName){if(typeof console!="undefined"){console.trace();console.error(this.handler," - error - ",c,c.message)}Strophe.fatal("error: "+this.handler+" "+c.fileName+":"+c.lineNumber+" - "+c.name+": "+c.message)}else Strophe.fatal("error: "+c.message+"\n"+c.stack);throw c;}return b},toString:function(){return"{Handler: "+
this.handler+"("+this.name+","+this.id+","+this.ns+")}"}};Strophe.TimedHandler=function(a,b){this.period=a;this.handler=b;this.lastCalled=(new Date).getTime();this.user=true};Strophe.TimedHandler.prototype={run:function(){this.lastCalled=(new Date).getTime();return this.handler()},reset:function(){this.lastCalled=(new Date).getTime()},toString:function(){return"{TimedHandler: "+this.handler+"("+this.period+")}"}};
Strophe.Request=function(a,b,c,d){this.id=++Strophe._requestId;this.xmlData=a;this.data=Strophe.serialize(a);this.func=this.origFunc=b;this.rid=c;this.date=NaN;this.sends=d||0;this.abort=false;this.dead=null;this.age=function(){return!this.date?0:(new Date-this.date)/1E3};this.timeDead=function(){return!this.dead?0:(new Date-this.dead)/1E3};this.xhr=this._newXHR()};
Strophe.Request.prototype={getResponse:function(){var a=null;if(this.xhr.responseXML&&this.xhr.responseXML.documentElement){a=this.xhr.responseXML.documentElement;if(a.tagName=="parsererror"){Strophe.error("invalid response received");Strophe.error("responseText: "+this.xhr.responseText);Strophe.error("responseXML: "+Strophe.serialize(this.xhr.responseXML));throw"parsererror";}}else if(this.xhr.responseText){Strophe.error("invalid response received");Strophe.error("responseText: "+this.xhr.responseText);
Strophe.error("responseXML: "+Strophe.serialize(this.xhr.responseXML))}return a},_newXHR:function(){var a=http.create();a.overrideMimeType&&a.overrideMimeType("text/xml");a.onreadystatechange=this.func.bind(null,this);return a}};
Strophe.Connection=function(a){this.service=a;this.jid="";this.domain=null;this.rid=Math.floor(Math.random()*4294967295);this.features=this.streamId=this.sid=null;this._sasl_data=[];this.do_bind=this.do_session=false;this.timedHandlers=[];this.handlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._authentication={};this._disconnectTimeout=this._idleTimeout=null;this.do_authentication=true;this.connected=this.disconnecting=this.authenticated=false;this.errors=
0;this.paused=false;this.hold=1;this.wait=60;this.window=5;this._data=[];this._requests=[];this._uniqueId=Math.round(Math.random()*1E4);this._sasl_challenge_handler=this._sasl_failure_handler=this._sasl_success_handler=null;this.maxRetries=5;this._idleTimeout=setTimeout(this._onIdle.bind(this),100);for(var b in Strophe._connectionPlugins)if(Strophe._connectionPlugins.hasOwnProperty(b)){a=function(){};a.prototype=Strophe._connectionPlugins[b];this[b]=new a;this[b].init(this)}};
Strophe.Connection.prototype={reset:function(){this.rid=Math.floor(Math.random()*4294967295);this.streamId=this.sid=null;this.do_bind=this.do_session=false;this.timedHandlers=[];this.handlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[];this._authentication={};this.connected=this.disconnecting=this.authenticated=false;this.errors=0;this._requests=[];this._uniqueId=Math.round(Math.random()*1E4)},pause:function(){this.paused=true},resume:function(){this.paused=
false},getUniqueId:function(a){return typeof a=="string"||typeof a=="number"?++this._uniqueId+":"+a:++this._uniqueId+""},connect:function(a,b,c,d,e,h){this.jid=a;this.pass=b;this.connect_callback=c;this.authenticated=this.connected=this.disconnecting=false;this.errors=0;this.wait=d||this.wait;this.hold=e||this.hold;this.domain=this.domain||Strophe.getDomainFromJid(this.jid);a=this._buildBody().attrs({to:this.domain,"xml:lang":"en",wait:this.wait,hold:this.hold,content:"text/xml; charset=utf-8",ver:"1.6",
"xmpp:version":"1.0","xmlns:xmpp":Strophe.NS.BOSH});h&&a.attrs({route:h});this._changeConnectStatus(Strophe.Status.CONNECTING,null);h=this._connect_callback||this._connect_cb;this._connect_callback=null;this._requests.push(new Strophe.Request(a.tree(),this._onRequestStateChange.bind(this,h.bind(this)),a.tree().getAttribute("rid")));this._throttledRequestHandler()},attach:function(a,b,c,d,e,h,g){this.jid=a;this.sid=b;this.rid=c;this.connect_callback=d;this.domain=Strophe.getDomainFromJid(this.jid);
this.connected=this.authenticated=true;this.wait=e||this.wait;this.hold=h||this.hold;this.window=g||this.window;this._changeConnectStatus(Strophe.Status.ATTACHED,null)},xmlInput:function(){},xmlOutput:function(){},rawInput:function(){},rawOutput:function(){},send:function(a){if(a!==null){if(typeof a.sort==="function")for(var b=0;b<a.length;b++)this._queueData(a[b]);else typeof a.tree==="function"?this._queueData(a.tree()):this._queueData(a);this._throttledRequestHandler();clearTimeout(this._idleTimeout);
this._idleTimeout=setTimeout(this._onIdle.bind(this),100)}},flush:function(){clearTimeout(this._idleTimeout);this._onIdle()},sendIQ:function(a,b,c,d){var e=null,h=this;typeof a.tree==="function"&&(a=a.tree());var g=a.getAttribute("id");if(!g){g=this.getUniqueId("sendIQ");a.setAttribute("id",g)}var m=this.addHandler(function(a){e&&h.deleteTimedHandler(e);var d=a.getAttribute("type");if(d=="result")b&&b(a);else if(d=="error")c&&c(a);else throw{name:"StropheError",message:"Got bad IQ type of "+d};},
null,"iq",null,g);d&&(e=this.addTimedHandler(d,function(){h.deleteHandler(m);c&&c(null);return false}));this.send(a);return g},_queueData:function(a){if(a===null||!a.tagName||!a.childNodes)throw{name:"StropheError",message:"Cannot queue non-DOMElement."};this._data.push(a)},_sendRestart:function(){this._data.push("restart");this._throttledRequestHandler();clearTimeout(this._idleTimeout);this._idleTimeout=setTimeout(this._onIdle.bind(this),100)},addTimedHandler:function(a,b){var c=new Strophe.TimedHandler(a,
b);this.addTimeds.push(c);return c},deleteTimedHandler:function(a){this.removeTimeds.push(a)},addHandler:function(a,b,c,d,e,h,g){a=new Strophe.Handler(a,b,c,d,e,h,g);this.addHandlers.push(a);return a},deleteHandler:function(a){this.removeHandlers.push(a)},disconnect:function(a){this._changeConnectStatus(Strophe.Status.DISCONNECTING,a);Strophe.info("Disconnect was called because: "+a);if(this.connected){this._disconnectTimeout=this._addSysTimedHandler(3E3,this._onDisconnectTimeout.bind(this));this._sendTerminate()}},
_changeConnectStatus:function(a,b){for(var c in Strophe._connectionPlugins)if(Strophe._connectionPlugins.hasOwnProperty(c)){var d=this[c];if(d.statusChanged)try{d.statusChanged(a,b)}catch(e){Strophe.error(""+c+" plugin caused an exception changing status: "+e)}}if(this.connect_callback)try{this.connect_callback(a,b)}catch(h){Strophe.error("User connection callback caused an exception: "+h)}},_buildBody:function(){var a=$build("body",{rid:this.rid++,xmlns:Strophe.NS.HTTPBIND});this.sid!==null&&a.attrs({sid:this.sid});
return a},_removeRequest:function(a){Strophe.debug("removing request");var b;for(b=this._requests.length-1;b>=0;b--)a==this._requests[b]&&this._requests.splice(b,1);a.xhr.onreadystatechange=function(){};this._throttledRequestHandler()},_restartRequest:function(a){var b=this._requests[a];if(b.dead===null)b.dead=new Date;this._processRequest(a)},_processRequest:function(a){var b=this._requests[a],c=-1;try{if(b.xhr.readyState==4)c=b.xhr.status}catch(d){Strophe.error("caught an error in _requests["+a+
"], reqStatus: "+c)}typeof c=="undefined"&&(c=-1);if(b.sends>this.maxRetries)this._onDisconnectTimeout();else{var e=b.age(),e=!isNaN(e)&&e>Math.floor(Strophe.TIMEOUT*this.wait),h=b.dead!==null&&b.timeDead()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait),c=b.xhr.readyState==4&&(c<1||c>=500);if(e||h||c){h&&Strophe.error("Request "+this._requests[a].id+" timed out (secondary), restarting");b.abort=true;b.xhr.abort();b.xhr.onreadystatechange=function(){};this._requests[a]=new Strophe.Request(b.xmlData,
b.origFunc,b.rid,b.sends);b=this._requests[a]}if(b.xhr.readyState===0){Strophe.debug("request id "+b.id+"."+b.sends+" posting");try{b.xhr.open("POST",this.service,true)}catch(g){Strophe.error("XHR open failed.");this.connected||this._changeConnectStatus(Strophe.Status.CONNFAIL,"bad-service");this.disconnect();return}a=function(){b.date=new Date;b.xhr.send(b.data)};if(b.sends>1){c=Math.min(Math.floor(Strophe.TIMEOUT*this.wait),Math.pow(b.sends,3))*1E3;setTimeout(a,c)}else a();b.sends++;this.xmlOutput!==
Strophe.Connection.prototype.xmlOutput&&this.xmlOutput(b.xmlData);this.rawOutput!==Strophe.Connection.prototype.rawOutput&&this.rawOutput(b.data)}else Strophe.debug("_processRequest: "+(a===0?"first":"second")+" request has readyState of "+b.xhr.readyState)}},_throttledRequestHandler:function(){this._requests?Strophe.debug("_throttledRequestHandler called with "+this._requests.length+" requests"):Strophe.debug("_throttledRequestHandler called with undefined requests");if(this._requests&&this._requests.length!==
0){this._requests.length>0&&this._processRequest(0);this._requests.length>1&&Math.abs(this._requests[0].rid-this._requests[1].rid)<this.window&&this._processRequest(1)}},_onRequestStateChange:function(a,b){Strophe.debug("request id "+b.id+"."+b.sends+" state changed to "+b.xhr.readyState);if(b.abort)b.abort=false;else{var c;if(b.xhr.readyState==4){c=0;try{c=b.xhr.status}catch(d){}typeof c=="undefined"&&(c=0);if(this.disconnecting&&c>=400)this._hitError(c);else{var e=this._requests[0]==b,h=this._requests[1]==
b;if(c>0&&c<500||b.sends>5){this._removeRequest(b);Strophe.debug("request id "+b.id+" should now be removed")}if(c==200){(h||e&&this._requests.length>0&&this._requests[0].age()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait))&&this._restartRequest(0);Strophe.debug("request id "+b.id+"."+b.sends+" got 200");a(b);this.errors=0}else{Strophe.error("request id "+b.id+"."+b.sends+" error "+c+" happened");if(c===0||c>=400&&c<600||c>=12E3){this._hitError(c);if(c>=400&&c<500){this._changeConnectStatus(Strophe.Status.DISCONNECTING,
null);this._doDisconnect()}}}c>0&&c<500||b.sends>5||this._throttledRequestHandler()}}}},_hitError:function(a){this.errors++;Strophe.warn("request errored, status: "+a+", number of errors: "+this.errors);this.errors>4&&this._onDisconnectTimeout()},_doDisconnect:function(){Strophe.info("_doDisconnect was called");this.disconnecting=this.authenticated=false;this.streamId=this.sid=null;this.rid=Math.floor(Math.random()*4294967295);if(this.connected){this._changeConnectStatus(Strophe.Status.DISCONNECTED,
null);this.connected=false}this.handlers=[];this.timedHandlers=[];this.removeTimeds=[];this.removeHandlers=[];this.addTimeds=[];this.addHandlers=[]},_dataRecv:function(a){try{var b=a.getResponse()}catch(c){if(c!="parsererror")throw c;this.disconnect("strophe-parsererror")}if(b!==null){this.xmlInput!==Strophe.Connection.prototype.xmlInput&&this.xmlInput(b);for(this.rawInput!==Strophe.Connection.prototype.rawInput&&this.rawInput(Strophe.serialize(b));this.removeHandlers.length>0;){a=this.removeHandlers.pop();
a=this.handlers.indexOf(a);a>=0&&this.handlers.splice(a,1)}for(;this.addHandlers.length>0;)this.handlers.push(this.addHandlers.pop());if(this.disconnecting&&this._requests.length===0){this.deleteTimedHandler(this._disconnectTimeout);this._disconnectTimeout=null;this._doDisconnect()}else{a=b.getAttribute("type");if(a!==null&&a=="terminate"){if(!this.disconnecting){a=b.getAttribute("condition");b=b.getElementsByTagName("conflict");if(a!==null){a=="remote-stream-error"&&b.length>0&&(a="conflict");this._changeConnectStatus(Strophe.Status.CONNFAIL,
a)}else this._changeConnectStatus(Strophe.Status.CONNFAIL,"unknown");this.disconnect()}}else{var d=this;Strophe.forEachChild(b,null,function(a){var b,c;c=d.handlers;d.handlers=[];for(b=0;b<c.length;b++){var m=c[b];try{m.isMatch(a)&&(d.authenticated||!m.user)?m.run(a)&&d.handlers.push(m):d.handlers.push(m)}catch(n){}}})}}}},_sendTerminate:function(){Strophe.info("_sendTerminate was called");var a=this._buildBody().attrs({type:"terminate"});this.authenticated&&a.c("presence",{xmlns:Strophe.NS.CLIENT,
type:"unavailable"});this.disconnecting=true;this._requests.push(new Strophe.Request(a.tree(),this._onRequestStateChange.bind(this,this._dataRecv.bind(this)),a.tree().getAttribute("rid")));this._throttledRequestHandler()},_connect_cb:function(a,b){Strophe.info("_connect_cb was called");this.connected=true;var c=a.getResponse();if(c){this.xmlInput!==Strophe.Connection.prototype.xmlInput&&this.xmlInput(c);this.rawInput!==Strophe.Connection.prototype.rawInput&&this.rawInput(Strophe.serialize(c));var d=
c.getAttribute("type");if(d!==null&&d=="terminate"){d=c.getAttribute("condition");c=c.getElementsByTagName("conflict");if(d!==null){d=="remote-stream-error"&&c.length>0&&(d="conflict");this._changeConnectStatus(Strophe.Status.CONNFAIL,d)}else this._changeConnectStatus(Strophe.Status.CONNFAIL,"unknown")}else{if(!this.sid)this.sid=c.getAttribute("sid");if(!this.stream_id)this.stream_id=c.getAttribute("authid");if(d=c.getAttribute("requests"))this.window=parseInt(d,10);if(d=c.getAttribute("hold"))this.hold=
parseInt(d,10);if(d=c.getAttribute("wait"))this.wait=parseInt(d,10);this._authentication.sasl_scram_sha1=false;this._authentication.sasl_plain=false;this._authentication.sasl_digest_md5=false;this._authentication.sasl_anonymous=false;this._authentication.legacy_auth=false;var e=c.getElementsByTagName("stream:features").length>0;e||(e=c.getElementsByTagName("features").length>0);var d=c.getElementsByTagName("mechanism"),h;h=false;if(e&&d.length>0){for(var g=0,e=0;e<d.length;e++){h=Strophe.getText(d.item(e));
h=="SCRAM-SHA-1"?this._authentication.sasl_scram_sha1=true:h=="DIGEST-MD5"?this._authentication.sasl_digest_md5=true:h=="PLAIN"?this._authentication.sasl_plain=true:h=="ANONYMOUS"?this._authentication.sasl_anonymous=true:g++}this._authentication.legacy_auth=c.getElementsByTagName("auth").length>0;h=this._authentication.legacy_auth||g<d.length}if(h)this.do_authentication!==false&&this.authenticate();else{b=b||this._connect_cb;c=this._buildBody();this._requests.push(new Strophe.Request(c.tree(),this._onRequestStateChange.bind(this,
b.bind(this)),c.tree().getAttribute("rid")));this._throttledRequestHandler()}}}},authenticate:function(){if(Strophe.getNodeFromJid(this.jid)===null&&this._authentication.sasl_anonymous){this._changeConnectStatus(Strophe.Status.AUTHENTICATING,null);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this.send($build("auth",{xmlns:Strophe.NS.SASL,
mechanism:"ANONYMOUS"}).tree())}else if(Strophe.getNodeFromJid(this.jid)===null){this._changeConnectStatus(Strophe.Status.CONNFAIL,"x-strophe-bad-non-anon-jid");this.disconnect()}else if(this._authentication.sasl_scram_sha1){var a=MD5.hexdigest(Math.random()*1234567890),b="n="+Strophe.getNodeFromJid(this.jid),b=b+",r="+a;this._sasl_data.cnonce=a;this._sasl_data["client-first-message-bare"]=b;b="n,,"+b;this._changeConnectStatus(Strophe.Status.AUTHENTICATING,null);this._sasl_challenge_handler=this._addSysHandler(this._sasl_scram_challenge_cb.bind(this),
null,"challenge",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this.send($build("auth",{xmlns:Strophe.NS.SASL,mechanism:"SCRAM-SHA-1"}).t(Base64.encode(b)).tree())}else if(this._authentication.sasl_digest_md5){this._changeConnectStatus(Strophe.Status.AUTHENTICATING,null);this._sasl_challenge_handler=this._addSysHandler(this._sasl_digest_challenge1_cb.bind(this),null,"challenge",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),
null,"failure",null,null);this.send($build("auth",{xmlns:Strophe.NS.SASL,mechanism:"DIGEST-MD5"}).tree())}else if(this._authentication.sasl_plain){b=Strophe.getBareJidFromJid(this.jid);b=b+"\x00"+Strophe.getNodeFromJid(this.jid);b=b+"\x00"+this.pass;this._changeConnectStatus(Strophe.Status.AUTHENTICATING,null);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,
"failure",null,null);hashed_auth_str=Base64.encode(b);this.send($build("auth",{xmlns:Strophe.NS.SASL,mechanism:"PLAIN"}).t(hashed_auth_str).tree())}else{this._changeConnectStatus(Strophe.Status.AUTHENTICATING,null);this._addSysHandler(this._auth1_cb.bind(this),null,null,null,"_auth_1");this.send($iq({type:"get",to:this.domain,id:"_auth_1"}).c("query",{xmlns:Strophe.NS.AUTH}).c("username",{}).t(Strophe.getNodeFromJid(this.jid)).tree())}},_sasl_digest_challenge1_cb:function(a){var b=/([a-z]+)=("[^"]+"|[^,"]+)(?:,|$)/,
c=Base64.decode(Strophe.getText(a)),a=MD5.hexdigest(""+Math.random()*1234567890),d="",e=null,h="",g;for(this.deleteHandler(this._sasl_failure_handler);c.match(b);){g=c.match(b);c=c.replace(g[0],"");g[2]=g[2].replace(/^"(.+)"$/,"$1");switch(g[1]){case "realm":d=g[2];break;case "nonce":h=g[2];break;case "host":e=g[2]}}b="xmpp/"+this.domain;e!==null&&(b=b+"/"+e);e=MD5.hash(Strophe.getNodeFromJid(this.jid)+":"+d+":"+this.pass)+":"+h+":"+a;c="AUTHENTICATE:"+b;g=""+("username="+this._quote(Strophe.getNodeFromJid(this.jid))+
",");g=g+("realm="+this._quote(d)+",");g=g+("nonce="+this._quote(h)+",");g=g+("cnonce="+this._quote(a)+",");g=g+'nc="00000001",qop="auth",'+("digest-uri="+this._quote(b)+",");g=g+("response="+this._quote(MD5.hexdigest(MD5.hexdigest(e)+":"+h+":00000001:"+a+":auth:"+MD5.hexdigest(c)))+",");g=g+'charset="utf-8"';this._sasl_challenge_handler=this._addSysHandler(this._sasl_digest_challenge2_cb.bind(this),null,"challenge",null,null);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),
null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this.send($build("response",{xmlns:Strophe.NS.SASL}).t(Base64.encode(g)).tree());return false},_quote:function(a){return'"'+a.replace(/\\/g,"\\\\").replace(/"/g,'\\"')+'"'},_sasl_digest_challenge2_cb:function(){this.deleteHandler(this._sasl_success_handler);this.deleteHandler(this._sasl_failure_handler);this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),
null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this.send($build("response",{xmlns:Strophe.NS.SASL}).tree());return false},_sasl_scram_challenge_cb:function(a){var b,c,d,e="c=biws,",h=Base64.decode(Strophe.getText(a)),a=this._sasl_data["client-first-message-bare"]+","+h+",",g=this._sasl_data.cnonce,m=/([a-z]+)=([^,]+)(,|$)/;for(this.deleteHandler(this._sasl_failure_handler);h.match(m);){matches=h.match(m);h=h.replace(matches[0],
"");switch(matches[1]){case "r":b=matches[2];break;case "s":c=matches[2];break;case "i":d=matches[2]}}if(b.substr(0,g.length)!==g){this._sasl_data=[];return this._sasl_failure_cb(null)}e=e+("r="+b);a=a+e;c=Base64.decode(c);b=c=core_hmac_sha1(this.pass,c+"\x00\x00\x00\u0001");for(i=1;i<d;i++){c=core_hmac_sha1(this.pass,binb2str(c));for(k=0;k<5;k++)b[k]=b[k]^c[k]}b=binb2str(b);d=core_hmac_sha1(b,"Client Key");b=str_hmac_sha1(b,"Server Key");c=core_hmac_sha1(str_sha1(binb2str(d)),a);this._sasl_data["server-signature"]=
b64_hmac_sha1(b,a);for(k=0;k<5;k++)d[k]=d[k]^c[k];e=e+(",p="+Base64.encode(binb2str(d)));this._sasl_success_handler=this._addSysHandler(this._sasl_success_cb.bind(this),null,"success",null,null);this._sasl_failure_handler=this._addSysHandler(this._sasl_failure_cb.bind(this),null,"failure",null,null);this.send($build("response",{xmlns:Strophe.NS.SASL}).t(Base64.encode(e)).tree());return false},_auth1_cb:function(){var a=$iq({type:"set",id:"_auth_2"}).c("query",{xmlns:Strophe.NS.AUTH}).c("username",
{}).t(Strophe.getNodeFromJid(this.jid)).up().c("password").t(this.pass);if(!Strophe.getResourceFromJid(this.jid))this.jid=Strophe.getBareJidFromJid(this.jid)+"/strophe";a.up().c("resource",{}).t(Strophe.getResourceFromJid(this.jid));this._addSysHandler(this._auth2_cb.bind(this),null,null,null,"_auth_2");this.send(a.tree());return false},_sasl_success_cb:function(a){if(this._sasl_data["server-signature"]){var b;matches=Base64.decode(Strophe.getText(a)).match(/([a-z]+)=([^,]+)(,|$)/);matches[1]=="v"&&
(b=matches[2]);if(b!=this._sasl_data["server-signature"]){this.deleteHandler(this._sasl_failure_handler);this._sasl_failure_handler=null;if(this._sasl_challenge_handler){this.deleteHandler(this._sasl_challenge_handler);this._sasl_challenge_handler=null}this._sasl_data=[];return this._sasl_failure_cb(null)}}Strophe.info("SASL authentication succeeded.");this.deleteHandler(this._sasl_failure_handler);this._sasl_failure_handler=null;if(this._sasl_challenge_handler){this.deleteHandler(this._sasl_challenge_handler);
this._sasl_challenge_handler=null}this._addSysHandler(this._sasl_auth1_cb.bind(this),null,"stream:features",null,null);this._sendRestart();return false},_sasl_auth1_cb:function(a){this.features=a;var b,c;for(b=0;b<a.childNodes.length;b++){c=a.childNodes.item(b);if(c.nodeName=="bind")this.do_bind=true;if(c.nodeName=="session")this.do_session=true}if(this.do_bind){this._addSysHandler(this._sasl_bind_cb.bind(this),null,null,null,"_bind_auth_2");(a=Strophe.getResourceFromJid(this.jid))?this.send($iq({type:"set",
id:"_bind_auth_2"}).c("bind",{xmlns:Strophe.NS.BIND}).c("resource",{}).t(a).tree()):this.send($iq({type:"set",id:"_bind_auth_2"}).c("bind",{xmlns:Strophe.NS.BIND}).tree())}else this._changeConnectStatus(Strophe.Status.AUTHFAIL,null);return false},_sasl_bind_cb:function(a){if(a.getAttribute("type")=="error"){Strophe.info("SASL binding failed.");var b;a.getElementsByTagName("conflict").length>0&&(b="conflict");this._changeConnectStatus(Strophe.Status.AUTHFAIL,b);return false}a=a.getElementsByTagName("bind");
if(a.length>0){a=a.item(0).getElementsByTagName("jid");if(a.length>0){this.jid=Strophe.getText(a.item(0));if(this.do_session){this._addSysHandler(this._sasl_session_cb.bind(this),null,null,null,"_session_auth_2");this.send($iq({type:"set",id:"_session_auth_2"}).c("session",{xmlns:Strophe.NS.SESSION}).tree())}else{this.authenticated=true;this._changeConnectStatus(Strophe.Status.CONNECTED,null)}}}else{Strophe.info("SASL binding failed.");this._changeConnectStatus(Strophe.Status.AUTHFAIL,null);return false}},
_sasl_session_cb:function(a){if(a.getAttribute("type")=="result"){this.authenticated=true;this._changeConnectStatus(Strophe.Status.CONNECTED,null)}else if(a.getAttribute("type")=="error"){Strophe.info("Session creation failed.");this._changeConnectStatus(Strophe.Status.AUTHFAIL,null)}return false},_sasl_failure_cb:function(){if(this._sasl_success_handler){this.deleteHandler(this._sasl_success_handler);this._sasl_success_handler=null}if(this._sasl_challenge_handler){this.deleteHandler(this._sasl_challenge_handler);
this._sasl_challenge_handler=null}this._changeConnectStatus(Strophe.Status.AUTHFAIL,null);return false},_auth2_cb:function(a){if(a.getAttribute("type")=="result"){this.authenticated=true;this._changeConnectStatus(Strophe.Status.CONNECTED,null)}else if(a.getAttribute("type")=="error"){this._changeConnectStatus(Strophe.Status.AUTHFAIL,null);this.disconnect()}return false},_addSysTimedHandler:function(a,b){var c=new Strophe.TimedHandler(a,b);c.user=false;this.addTimeds.push(c);return c},_addSysHandler:function(a,
b,c,d,e){a=new Strophe.Handler(a,b,c,d,e);a.user=false;this.addHandlers.push(a);return a},_onDisconnectTimeout:function(){Strophe.info("_onDisconnectTimeout was called");for(var a;this._requests.length>0;){a=this._requests.pop();a.abort=true;a.xhr.abort();a.xhr.onreadystatechange=function(){}}this._doDisconnect();return false},_onIdle:function(){for(var a,b,c,d;this.addTimeds.length>0;)this.timedHandlers.push(this.addTimeds.pop());for(;this.removeTimeds.length>0;){b=this.removeTimeds.pop();a=this.timedHandlers.indexOf(b);
a>=0&&this.timedHandlers.splice(a,1)}var e=(new Date).getTime();d=[];for(a=0;a<this.timedHandlers.length;a++){b=this.timedHandlers[a];if(this.authenticated||!b.user){c=b.lastCalled+b.period;c-e<=0?b.run()&&d.push(b):d.push(b)}}this.timedHandlers=d;if(this.authenticated&&this._requests.length===0&&this._data.length===0&&!this.disconnecting){Strophe.info("no requests during idle cycle, sending blank request");this._data.push(null)}if(this._requests.length<2&&this._data.length>0&&!this.paused){b=this._buildBody();
for(a=0;a<this._data.length;a++)this._data[a]!==null&&(this._data[a]==="restart"?b.attrs({to:this.domain,"xml:lang":"en","xmpp:restart":"true","xmlns:xmpp":Strophe.NS.BOSH}):b.cnode(this._data[a]).up());delete this._data;this._data=[];this._requests.push(new Strophe.Request(b.tree(),this._onRequestStateChange.bind(this,this._dataRecv.bind(this)),b.tree().getAttribute("rid")));this._processRequest(this._requests.length-1)}if(this._requests.length>0){a=this._requests[0].age();this._requests[0].dead!==
null&&this._requests[0].timeDead()>Math.floor(Strophe.SECONDARY_TIMEOUT*this.wait)&&this._throttledRequestHandler();if(a>Math.floor(Strophe.TIMEOUT*this.wait)){Strophe.warn("Request "+this._requests[0].id+" timed out, over "+Math.floor(Strophe.TIMEOUT*this.wait)+" seconds since last activity");this._throttledRequestHandler()}}clearTimeout(this._idleTimeout);if(this.connected)this._idleTimeout=setTimeout(this._onIdle.bind(this),100)}};
